version: '3.9'
services:
  backend:
    container_name: server-dev
    image: node:14
    tty: true
    working_dir: /usr/src/app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    # networks:
    #   - server-network
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: postgres
    hostname: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: nestjs@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
